import { fixSlider } from "./components/fixSlider";
import { fixHeader } from "./components/fixHeder";
import { fixFooterBanner } from "./components/fixFooterBanner";
import { slickSlider } from "./components/slickSlider";
import { smoothScroll } from "./components/smoothScroll";
// import { showOnScroll } from "./components/showOnScroll";
import { swiperSlider } from "./components/swiperSlider";
// import { toggleNavigation } from "./components/toggleNavigation";
// import { scrollToTop } from "./components/scrollTotop";
import { faqAccordion } from "./components/faqAccordion";

fixHeader();
fixFooterBanner();
faqAccordion();
slickSlider();
fixSlider();
smoothScroll();
// showOnScroll();
swiperSlider();
// scrollToTop();
// toggleNavigation();
